### ISSUE TITLE
Does this module support checking for a particular service over a port?

### ISSUE THREAD

**Issue by OvernightSuccess123** [XBCreepinJesus/MMM-ServerStatus#7]
For example, if I want to check if MagicMirror server is running on port 8080.

I can check the IP address ping, but that only checks if that device is pingable, not the service running on port 8080.

**Comment by XBCreepinJesus** [comment]
Hi. Sorry for the delayed response!

You can't do that with the 'ping' command, as far as I know, but I think you can use other tools such as telnet or nmap to check if certain ports are reachable.

So, no, that can't be done with this module in its current form, but if you want to make your own version that uses a different program then go for it!
